import { IncomingMessage } from 'http'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Ethan Skinner</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Image className={styles.round}src="/confetti.jpg" alt="Ethan Skinner profile pic" height={300} width={300} layout="intrinsic" objectFit='cover' objectPosition='center'/>
    </div>
  )
}

export default Home
